name: "Sentryfuge"
description: "Automatically link referenced Sentry issues in issues and PRs"
inputs:
  sentry_base:
    description: "Your Sentry instance URL. Defaults to sentry.io"
    required: true
    default: "https://sentry.io/"
  org_slug:
    description: "Your Sentry organization slug"
    required: true
  project_prefixes:
    description: "A list of valid Sentry project prefixes, separated by new lines"
    required: true
  github_token:
    description: "GITHUB_TOKEN to act on the issues. Needs write permissions for PRs and issues"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  color: yellow
  icon: arrow-up-right
